# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-28 15:14
from __future__ import unicode_literals

import Database.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignDeveloper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator', models.CharField(max_length=200)),
                ('commentDescription', models.TextField(blank=True)),
                ('commentTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileNames', models.TextField(blank=True)),
                ('done_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=Database.models.file_upload_path)),
                ('fileName', models.CharField(max_length=200)),
                ('fileDescription', models.TextField(blank=True)),
                ('fileSize', models.IntegerField()),
                ('fileType', models.CharField(max_length=15)),
                ('modificationTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='InProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileNames', models.TextField(blank=True)),
                ('inProgress_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=200)),
                ('label', models.CharField(default='Help Wanted', max_length=100)),
                ('issueDescription', models.TextField()),
                ('isClosed', models.BooleanField(default=False)),
                ('issueTime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isViewed', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('link', models.URLField()),
                ('sender', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=250)),
                ('projectDescription', models.TextField()),
                ('accessType', models.CharField(default='Public', max_length=25)),
                ('projectCreatedAt', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('skilltag', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('C', 'C'), ('C++', 'C++'), ('JAVA', 'JAVA'), ('PYTHON', 'PYTHON'), ('RUBY', 'RUBY'), ('C#', 'C#'), ('FORTRAN', 'FORTRAN'), ('JAVASCRIPT', 'JAVASCRIPT'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('PHP', 'PHP')], default='NONE', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Project')),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='None', max_length=200)),
                ('biography', models.TextField(default='None')),
                ('profilePicture', models.FileField(default='../media/defaultProfilePic.png', upload_to=Database.models.user_directory_path)),
                ('skilltag', multiselectfield.db.fields.MultiSelectField(choices=[('C', 'C'), ('C++', 'C++'), ('JAVA', 'JAVA'), ('PYTHON', 'PYTHON'), ('RUBY', 'RUBY'), ('C#', 'C#'), ('FORTRAN', 'FORTRAN'), ('JAVASCRIPT', 'JAVASCRIPT'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('PHP', 'PHP')], default='NONE', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileContent', models.TextField(default='First File')),
                ('versionDescription', models.TextField(blank=True)),
                ('versionFilename', models.CharField(max_length=200)),
                ('versionFileSize', models.IntegerField()),
                ('versionModificationTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.File')),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='issueCreator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Project'),
        ),
        migrations.AddField(
            model_name='inprogress',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Project'),
        ),
        migrations.AddField(
            model_name='inprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Project'),
        ),
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='done',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Project'),
        ),
        migrations.AddField(
            model_name='done',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.File'),
        ),
        migrations.AddField(
            model_name='assigndeveloper',
            name='assignDeveloper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assigndeveloper',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Project'),
        ),
    ]
