# Generated by Django 2.0.3 on 2018-04-03 09:04

import Database.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skilltag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UsersAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('userName', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('biography', models.TextField()),
                ('profilePicture', models.FileField(upload_to=Database.models.user_directory_path)),
            ],
        ),
        migrations.AddField(
            model_name='skilltag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.UsersAll'),
        ),
    ]
