# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-14 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilltag',
            name='name',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='skilltag',
            field=models.ManyToManyField(blank=True, to='Database.SkillTag'),
        ),
    ]
