# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-08 22:18
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_auto_20180509_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skilltag',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('C', 'C'), ('C++', 'C++'), ('JAVA', 'JAVA'), ('PYTHON', 'PYTHON'), ('RUBY', 'RUBY'), ('C#', 'C#'), ('FORTRAN', 'FORTRAN'), ('JAVASCRIPT', 'JAVASCRIPT'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('PHP', 'PHP')], default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='skilltag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('C', 'C'), ('C++', 'C++'), ('JAVA', 'JAVA'), ('PYTHON', 'PYTHON'), ('RUBY', 'RUBY'), ('C#', 'C#'), ('FORTRAN', 'FORTRAN'), ('JAVASCRIPT', 'JAVASCRIPT'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('PHP', 'PHP')], default='NONE', max_length=200),
        ),
    ]
