# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-14 04:44
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_auto_20180414_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltag',
            name='skilltag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('C', 'C'), ('C++', 'C++'), ('JAVA', 'JAVA'), ('PYTHON', 'PYTHON')], max_length=20),
        ),
    ]
