# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-04 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_auto_20180505_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='done',
            name='file',
        ),
        migrations.RemoveField(
            model_name='inprogress',
            name='file',
        ),
        migrations.AddField(
            model_name='done',
            name='fileNames',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inprogress',
            name='fileNames',
            field=models.TextField(blank=True),
        ),
    ]
