# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-14 07:54
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_auto_20180414_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='skilltag',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='skilltag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('C', 'C'), ('C++', 'C++'), ('JAVA', 'JAVA'), ('PYTHON', 'PYTHON')], default='NONE', max_length=20),
        ),
        migrations.DeleteModel(
            name='SkillTag',
        ),
    ]
