# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-14 10:24
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0004_auto_20180414_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='skilltag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('C', 'C'), ('C++', 'C++'), ('JAVA', 'JAVA'), ('PYTHON', 'PYTHON'), ('RUBY', 'RUBY'), ('C#', 'C#'), ('FORTRAN', 'FORTRAN'), ('JAVASCRIPT', 'JAVASCRIPT'), ('HTML', 'HTML'), ('CSS', 'CSS')], default='NONE', max_length=20),
        ),
    ]
