# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-09 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentator',
            field=models.CharField(max_length=200),
        ),
    ]
