# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-15 09:29
from __future__ import unicode_literals

import Database.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Database', '0006_auto_20180414_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Database.models.file_upload_path)),
                ('fileName', models.CharField(max_length=200)),
                ('fileDescription', models.TextField(blank=True)),
                ('fileSize', models.IntegerField()),
                ('fileType', models.CharField(max_length=15)),
                ('modificationTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
