# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-16 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0007_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileContent', models.TextField(default='First File')),
                ('versionDescription', models.TextField(blank=True)),
                ('versionFilename', models.CharField(max_length=200)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.File')),
            ],
        ),
    ]
